### ISSUE TITLE
1. Introducing Dictionaries & Optionals - minor typos

### ISSUE THREAD

**Issue by vronlin** [MakeSchool-Tutorials/Dictionaries-Optionals-Swift#1]
PAGE 4: DICTIONARIES

<img width="793" alt="screen shot 2016-06-29 at 4 16 43 pm" src="https://cloud.githubusercontent.com/assets/19824721/16471939/205371e4-3e15-11e6-8f6d-697ee2e57bd0.png">
"the key would be the **WORD** _(not world)_"

<img width="756" alt="screen shot 2016-06-29 at 4 21 15 pm" src="https://cloud.githubusercontent.com/assets/19824721/16472001/8caecb72-3e15-11e6-9baf-2a8d0e7304de.png">
"Well, we cannot **GUARANTEE** _(not guarentee)_ the key is actually in the dictionary. This means that we cannot **GUARANTEE** _(not guarenteed)_ we'll actually get a value back."

PAGE 5: CHALLENGE

<img width="727" alt="screen shot 2016-06-29 at 4 24 46 pm" src="https://cloud.githubusercontent.com/assets/19824721/16472057/0718b1f2-3e16-11e6-8b89-43124ae00c8c.png">
"This will store name Strings as keys **AND** _(not an)_ phone number Strings as values"

<img width="734" alt="screen shot 2016-06-29 at 4 26 22 pm" src="https://cloud.githubusercontent.com/assets/19824721/16472083/3ec99a94-3e16-11e6-8415-361b4aea2920.png">
"If the contact exists in your phone book, it should print "<contact name> has been updated **IN** _(previously missing in)_ your phone book.""

**Comment by dionlarson** [comment]
Fixed. Thank you!
